### ISSUE TITLE
5G Cellular Network Design and the number of hops

### ISSUE THREAD

**Issue by mraavi5** [Verizon/verizon.github.io#10]
Hi

This is a question and not an issue.

I'm looking for the cellular network design best-case scenarios and couldn't find any Verizon or any other cellular network design. I understand that these might be confidential. If it's not,

Is there a place where we can find Verizon or any other cellular network design? (I know 3GPP 5G standards.)
I'm interested in real-world implementations and knowing about the functions hosted on VM's and the number of hops between them.
Which functions can be hosted on the same machine versus which functions need to be hosted separately

Thank you

**Comment by hahla** [comment]
Hi @mraavi5, 

Occasionally we give presentations at conferences such as [this one](https://www.youtube.com/watch?v=AbtL6j6XL8U). Have a look, I hope you find it useful. But generally, we don't publish such info online.

If you have a business interest, also you can contact our Verizon Business Group. https://www.verizon.com/business/

Best,
Michael
