### ISSUE TITLE
right side of page header is cut off when viewport aspect ratio is 4:3

### ISSUE THREAD

**Issue by jpelton-stroud** [Verizon/verizon.github.io#11]
Issue is particularly apparent at `vw: 1280px`, but starts appearing around `vw: 1400px`.

screenshot for ref, `Chrome v94.0.4606.81`

![1280x1024](https://user-images.githubusercontent.com/41320448/136601872-8c47f341-f395-47cb-a134-6c09543fbd12.png)

**Comment by aserputov** [comment]
Hello, I want to fix this, can you please assign me ? @jpelton-stroud

**Comment by GaryPWhite** [comment]
closed for inactivity
