### ISSUE TITLE
Verizon Quantum G1100 Firmware install

### ISSUE THREAD

**Issue by KurtStam** [Verizon/verizon.github.io#5]
Hi,

I bought a Quantum G1100, but it has Frontier firmware running on it. I see you publish your own firmware tars here:

https://www.verizon.com/support/consumer/internet/open-source-software-portal?CMP=DMC-CVZ_ZZ_ZZ_Z_DO_N_X00366

I found a /advanced/fwupgrade endpoint in the frontier firmware but it limits filesize to about 50mb, and it need to be signed (by frontier?). So that kinda stops me dead.

There must be another way to install the Verizon firmware? You are publishing the firmware.. why not the instructions on how to install it.

Thx,

--Kurt

**Comment by coding-saints** [comment]
No response yet? I'm wondering if getting involved is even an option, or are they simply hosting here. It'd be nice to be able to contribute to some of the issues on here.
