### ISSUE TITLE
"Open Source home page of Verizon" to "Open Source Verizon's GitHub home page"

### ISSUE THREAD

**Issue by imthenachoman** [Verizon/verizon.github.io#9]
Hopefully I'm not being a bit pedantic but I am going to assume this repo is not for verizon.com but rather verizon.github.io. 

I wouldn't want some poor soul thinking this is the code to our verizon.com page.

**Comment by vamsiponnapalli** [comment]
Haha great callout! I just changed the About section to include your recommended text. Is there anywhere else you see the wording should be changed?
